# Reveal Project Configuration
# Version: v0.28.0+
# This config demonstrates reveal's configuration capabilities
# while ensuring the project itself passes quality checks.

root: true  # Stop searching upward for parent configs

# Rule configuration
rules:
  # Complexity thresholds - balanced for production code
  # Note: Infrastructure code (config.py) is inherently complex due to:
  #   - 7-level configuration precedence merging
  #   - Directory tree walking and config discovery
  #   - Environment variable parsing with validation
  C901:
    threshold: 21  # Cyclomatic complexity (default: 10)
                   # Allows infrastructure code patterns

  C905:
    MAX_DEPTH: 6   # Max nesting depth (default: 4)
                   # Allows directory tree walking patterns

  # Line length - reasonable for modern displays
  E501:
    max_length: 100  # Default is 100, made explicit

  # Function parameters
  R913:
    max_args: 5  # Default is 5, made explicit

  # Disable specific rules (currently none)
  # Uncomment and add rules as needed:
  # disable:
  #   - E501  # Line too long
  #   - C901  # Too complex

# Files and directories to ignore
ignore:
  # Build artifacts
  - "*.egg-info/**"
  - "build/**"
  - "dist/**"
  - "__pycache__/**"
  - ".pytest_cache/**"
  - ".ruff_cache/**"
  - "htmlcov/**"
  - ".coverage"
  - "coverage.json"

  # External dependencies
  - ".benchmarks/**"
  - "external-git/**"  # Nested git repos

  # Generated files
  - "*.pyc"
  - "*.pyo"
  - "*.so"

  # Temporary files
  - "*.tmp"
  - "*.bak"
  - "*~"

# File-specific overrides
overrides:
  - files: "reveal/rules/**/*.py"
    rules:
      disable:
        - M102  # Rules are discovered dynamically via importlib, not static imports
  - files: "reveal/templates/**/*.py"
    rules:
      disable:
        - M102  # Template scaffolding files are intentionally not imported at runtime
  - files: "reveal/adapters/ast/adapter.py"
    rules:
      disable:
        - V023  # Contract fields added by ResultBuilder (utils/results.py)
  - files: "reveal/adapters/git/adapter.py"
    rules:
      disable:
        - V023  # Contract fields added by helper modules (files.py, commits.py, refs.py)
  - files: "reveal/adapters/imports.py"
    rules:
      disable:
        - V023  # Contract fields added by _format_all() and other helper methods
  - files: "reveal/adapters/json/adapter.py"
    rules:
      disable:
        - V023  # Contract fields added by _build_success_result() and other helpers
  - files: "reveal/adapters/xlsx.py"
    rules:
      disable:
        - V023  # Contract fields added by ResultBuilder in helper methods
  - files: "reveal/result.py"
    rules:
      disable:
        - D001  # Result monad: Success/Failure intentionally have same-body methods (is_success/is_failure)
