"""BACK-1623: claude:// checked against an independent parser on 10,021 local sessions.

Each test reproduces a record shape taken from real Claude Code transcripts on which
the adapter's answer differed from the raw JSONL.
"""
import json
from pathlib import Path

from reveal.adapters.claude.adapter import ClaudeAdapter
from reveal.adapters.claude.analysis.errors import get_errors
from reveal.adapters.claude.analysis.messages import (
    get_exchanges,
    get_human_prompts,
    get_thinking_blocks,
)
from reveal.adapters.claude.analysis.overview import get_overview, get_token_breakdown
from reveal.adapters.claude.analysis.tools import get_all_tools


def _cb():
    return {'contract_version': '1.0', 'source': 'test', 'source_type': 'file'}


def _rec(type_, uuid, parent, content=None, **extra):
    record = {'type': type_, 'uuid': uuid, 'parentUuid': parent,
              'timestamp': '2026-10-01T10:00:00Z', 'message': {'content': content if content is not None else []}}
    record.update(extra)
    return record


def _assistant(uuid, parent, block, msg_id, stop_reason, usage):
    record = _rec('assistant', uuid, parent, [block])
    record['message'].update({'id': msg_id, 'stop_reason': stop_reason, 'usage': usage})
    return record


def _usage(inp, out, read, created):
    return {'input_tokens': inp, 'output_tokens': out,
            'cache_read_input_tokens': read, 'cache_creation_input_tokens': created}


class TestTokenTotalsPerApiMessage:
    """One record per content block, each repeating the message's usage; stop_reason on 0..n of them."""

    def _session(self):
        return [
            _rec('user', 'p1', None, 'go'),
            # msg_A: stop_reason on both records (seen on 39% of messages) -> was counted twice
            _assistant('a1', 'p1', {'type': 'thinking', 'thinking': ''}, 'msg_A', 'tool_use', _usage(6, 156, 16445, 21733)),
            _assistant('a2', 'a1', {'type': 'tool_use', 'id': 't1', 'name': 'Bash', 'input': {}}, 'msg_A', 'tool_use', _usage(6, 156, 16445, 21733)),
            _rec('user', 'r1', 'a2', [{'type': 'tool_result', 'tool_use_id': 't1', 'content': 'ok'}]),
            # msg_B: no record has stop_reason (22% of messages) -> was dropped; output grows while streaming
            _assistant('b1', 'r1', {'type': 'text', 'text': 'Done.'}, 'msg_B', None, _usage(1511, 1, 33131, 28775)),
            _assistant('b2', 'b1', {'type': 'text', 'text': 'Done, really.'}, 'msg_B', None, _usage(1511, 40, 33131, 28775)),
        ]

    def test_overview_sums_each_api_message_once(self):
        totals = get_overview(self._session(), 's', '', _cb())['token_summary']
        assert totals['input_tokens'] == 6 + 1511
        assert totals['output_tokens'] == 156 + 40
        assert totals['cache_read_tokens'] == 16445 + 33131
        assert totals['cache_created_tokens'] == 21733 + 28775
        assert totals['messages_with_usage'] == 2

    def test_token_breakdown_has_one_entry_per_api_message(self):
        result = get_token_breakdown(self._session(), 's', _cb())
        assert [e['message_index'] for e in result['messages']] == [1, 4]
        assert result['messages'][1]['output_tokens'] == 40
        assert result['totals']['output_tokens'] == 196
        assert result['messages'][-1]['cumulative_input'] == (6 + 16445 + 21733) + (1511 + 33131 + 28775)


class TestPromptsAreHumanTyped:

    def _session(self):
        return [
            _rec('user', 'p1', None, 'real question'),
            _rec('user', 'm1', 'p1', 'Caveat: The messages below were generated by the user while running local commands.', isMeta=True),
            _rec('user', 'm2', 'm1', [{'type': 'text', 'text': '[Image: source: /home/u/.claude/image-cache/x.png]'}], isMeta=True),
            _rec('user', 'b1', 'm2', '<bash-input>ls</bash-input>'),
            _rec('user', 'b2', 'b1', '<bash-stdout>README.md</bash-stdout><bash-stderr></bash-stderr>'),
            _rec('user', 'c1', 'b2', 'This session is being continued from a previous conversation that ran out of context.',
                 isCompactSummary=True, isVisibleInTranscriptOnly=True),
            _rec('user', 'p2', 'c1', 'second real question'),
        ]

    def test_harness_records_and_bash_output_are_not_prompts(self):
        result = get_human_prompts(self._session(), 's', _cb())
        assert [m['message_index'] for m in result['messages']] == [0, 6]

    def test_exchanges_pair_only_human_prompts(self):
        result = get_exchanges(self._session(), 's', _cb())
        assert [e['message_index'] for e in result['exchanges']] == [0, 6]


class TestExchangeAnswerAcrossParallelToolCalls:

    def test_answer_is_the_reply_after_all_parallel_results(self):
        # One assistant message with two tool_use blocks -> two records chained u1 -> u2,
        # and each result hangs off its own tool_use record. In the real shape the reply
        # continues from the FIRST call's result r1, while u2's branch ends at r2. A
        # first-child walk took u1 -> u2 -> r2 (a leaf) and returned the early
        # "Let me check" line.
        messages = [
            _rec('user', 'p1', None, 'check both'),
            _rec('assistant', 'a0', 'p1', [{'type': 'text', 'text': 'Let me check both.'}]),
            _rec('assistant', 'u1', 'a0', [{'type': 'tool_use', 'id': 't1', 'name': 'Bash', 'input': {}}]),
            _rec('assistant', 'u2', 'u1', [{'type': 'tool_use', 'id': 't2', 'name': 'Bash', 'input': {}}]),
            _rec('user', 'r2', 'u2', [{'type': 'tool_result', 'tool_use_id': 't2', 'content': 'b'}]),
            _rec('user', 'r1', 'u1', [{'type': 'tool_result', 'tool_use_id': 't1', 'content': 'a'}]),
            _rec('assistant', 'f1', 'r1', [{'type': 'text', 'text': 'Both are fine.'}]),
            _rec('user', 'p2', 'f1', 'thanks'),
        ]
        ex = get_exchanges(messages, 's', _cb())['exchanges'][0]
        assert ex['answer'] == 'Both are fine.'
        assert ex['answer_message_index'] == 6

    def test_answer_survives_a_compaction_boundary_mid_turn(self):
        # A compact_boundary re-roots the chain (parentUuid None), so the walk back from
        # the next prompt never reaches this prompt; the tail it walked is still the turn.
        messages = [
            _rec('user', 'p1', None, 'long task'),
            _rec('assistant', 'a1', 'p1', [{'type': 'text', 'text': 'Starting.'}]),
            _rec('system', 'cb', None, subtype='compact_boundary'),
            _rec('assistant', 'a2', 'cb', [{'type': 'text', 'text': 'Finished the long task.'}]),
            _rec('user', 'p2', 'a2', 'next'),
        ]
        ex = get_exchanges(messages, 's', _cb())['exchanges'][0]
        assert ex['answer'] == 'Finished the long task.'


class TestErrorHeuristicsReadCommandOutputOnly:

    def _session(self, tool_name, output):
        return [
            _rec('user', 'p1', None, 'go'),
            _rec('assistant', 'a1', 'p1', [{'type': 'tool_use', 'id': 't1', 'name': tool_name, 'input': {}}]),
            _rec('user', 'r1', 'a1', [{'type': 'tool_result', 'tool_use_id': 't1', 'content': output}]),
        ]

    def test_file_contents_are_not_an_error(self):
        doc = '     1→# Notes\n     2→Without it, md-to-pdf silently fails (exit code 2, no output).\n     3→Error: handling is covered below\n'
        messages = self._session('Read', doc)
        assert get_errors(messages, 's', _cb())['error_count'] == 0
        assert get_all_tools(messages, 's', _cb())['tools']['Read']['failure'] == 0

    def test_command_output_still_is(self):
        messages = self._session('Bash', 'Traceback (most recent call last):\n  File "x.py", line 1\nValueError: bad')
        assert get_errors(messages, 's', _cb())['errors'][0]['error_type'] == 'pattern_match'
        assert get_all_tools(messages, 's', _cb())['tools']['Bash']['failure'] == 1

    def test_errors_honors_return_code_interpretation_like_tools(self):
        messages = self._session('Bash', 'Error: not really, the client says success')
        messages[2]['toolUseResult'] = {'returnCodeInterpretation': 'success', 'stdout': ''}
        assert get_errors(messages, 's', _cb())['error_count'] == 0
        assert get_all_tools(messages, 's', _cb())['tools']['Bash']['failure'] == 0


class TestSessionWithSeveralTranscripts:

    def _write(self, path: Path, first_ts: str):
        path.write_text(json.dumps({'type': 'user', 'timestamp': first_ts, 'uuid': path.stem,
                                    'message': {'content': 'hi'}}) + '\n', encoding='utf-8')

    def test_first_started_transcript_is_read_and_the_rest_disclosed(self, tmp_path):
        session_dir = tmp_path / '-home-u-src-tia-sessions-xenon-wolf-0829'
        session_dir.mkdir()
        names = ['b8b981fd-0000-0000-0000-000000000000', '24e2d55a-0000-0000-0000-000000000000',
                 'b7ae9f24-0000-0000-0000-000000000000']
        for name, ts in zip(names, ['2026-08-29T12:00:00Z', '2026-08-29T09:00:00Z', '2026-08-29T15:00:00Z']):
            self._write(session_dir / f'{name}.jsonl', ts)
        # A scratchpad dir that also carries the session name must not win.
        scratch = tmp_path / '-tmp-claude-1000--home-u-src-tia-sessions-xenon-wolf-0829-abc-scratchpad'
        scratch.mkdir()
        self._write(scratch / 'ffffffff-0000-0000-0000-000000000000.jsonl', '2026-08-29T01:00:00Z')

        adapter = ClaudeAdapter.__new__(ClaudeAdapter)
        adapter.session_name = 'xenon-wolf-0829'
        adapter.CONVERSATION_BASE = tmp_path
        assert adapter._find_conversation() == session_dir / f'{names[1]}.jsonl'

        result: dict = {}
        adapter.conversation_path = session_dir / f'{names[1]}.jsonl'
        adapter._disclose_other_transcripts(result)
        warning = result['meta']['warnings'][0]
        assert warning['type'] == 'other_transcripts' and warning['count'] == 2
        assert f'claude://session/{names[0]}' in warning['message']
        assert f'claude://session/{names[2]}' in warning['message']

    def test_single_transcript_has_no_warning(self, tmp_path):
        session_dir = tmp_path / '-home-u-src-tia-sessions-solo-0101'
        session_dir.mkdir()
        self._write(session_dir / 'aaaaaaaa-0000-0000-0000-000000000000.jsonl', '2026-01-01T00:00:00Z')
        adapter = ClaudeAdapter.__new__(ClaudeAdapter)
        adapter.session_name = 'solo-0101'
        adapter.CONVERSATION_BASE = tmp_path
        adapter.conversation_path = adapter._find_conversation()
        result: dict = {}
        adapter._disclose_other_transcripts(result)
        assert 'meta' not in result


def test_thinking_counts_blocks_without_text():
    messages = [
        _rec('assistant', 'a1', None, [{'type': 'thinking', 'thinking': '', 'signature': 'sig'}]),
        _rec('assistant', 'a2', 'a1', [{'type': 'thinking', 'thinking': 'Plan: check the tests.', 'signature': 'sig'}]),
    ]
    result = get_thinking_blocks(messages, 's', _cb())
    assert result['thinking_block_count'] == 2
    assert result['blocks_without_text'] == 1
