"""File checking operations (schema validation, pattern detection).

This module is separate from main.py to avoid circular dependencies with cli.routing.
"""

import os
import re
import sys
from collections import defaultdict
from typing import Optional, Any, List

from .base import FileAnalyzer
from .utils import safe_json_dumps, get_file_type_from_analyzer, print_breadcrumbs

# When a single rule fires this many times in one file, collapse to a summary line.
# Users can disable with --no-group.
_GROUP_THRESHOLD = 10

# Patterns indicating a file is auto-generated and should be skipped in recursive --check.
#
# BACK-1195: was anchored to `#`-prefixed comments only, so a C/JS-style
# `/* @generated */` or `// generated` header couldn't match by construction
# (confirmed live, wishlist-3 addendum B3-4). Each pattern now accepts an
# optional `#`, `//`, or `/*` comment lead-in (or none at all, for engines
# that emit a bare marker line).
_COMMENT_LEAD_IN = r'(?:#|//|/\*)?\s*'
_GENERATED_PATTERNS = [
    re.compile(_COMMENT_LEAD_IN + r'reveal:\s*generated', re.IGNORECASE),
    re.compile(_COMMENT_LEAD_IN + r'(this file (is|was)\s+)?(auto[- ]?generated|automatically generated)', re.IGNORECASE),
    re.compile(_COMMENT_LEAD_IN + r'Generated by\b', re.IGNORECASE),
    re.compile(_COMMENT_LEAD_IN + r'@generated\b', re.IGNORECASE),
]


def _is_generated_file(content: str) -> bool:
    """Return True if content appears to be auto-generated (first 15 lines)."""
    head = '\n'.join(content.splitlines()[:15])
    return any(p.search(head) for p in _GENERATED_PATTERNS)


def _format_detections_json(
    path: str,
    detections: List[Any],
    parse_degraded: bool = False,
    rule_errors: Optional[List[dict]] = None,
    no_snippets: bool = False,
    max_snippet_chars: Optional[int] = None,
    total_available: Optional[int] = None,
) -> None:
    """Format detections as JSON.

    Args:
        path: File path
        detections: List of Detection objects (already max-items-truncated
            by the caller, if requested — this just renders what it's given)
        parse_degraded: True when the parser recovered from a syntax error
            (BACK-1084's structure['_has_errors']) — detections/structure for
            this file may be incomplete or wrong, not just "clean" (BACK-1083).
        rule_errors: Rules that raised during check() ({"rule", "error"}, from
            RuleRegistry.check_file's errors= param) — otherwise invisible on
            stdout/JSON, visible only in the stderr log (BACK-1083).
        no_snippets: Omit each detection's `context` (code excerpt) field
            (BACK-1182).
        max_snippet_chars: Truncate each detection's `context` to N chars
            instead of omitting it (BACK-1181). Ignored when no_snippets.
        total_available: True detection count before any --max-items
            truncation, if different from len(detections) (BACK-1181).
    """
    print(safe_json_dumps(_build_detections_json(
        path, detections, parse_degraded=parse_degraded, rule_errors=rule_errors,
        no_snippets=no_snippets, max_snippet_chars=max_snippet_chars,
        total_available=total_available,
    )))


def _build_detections_json(
    path: str,
    detections: List[Any],
    parse_degraded: bool = False,
    rule_errors: Optional[List[dict]] = None,
    no_snippets: bool = False,
    max_snippet_chars: Optional[int] = None,
    total_available: Optional[int] = None,
) -> dict:
    """Build the single-file check JSON document. Split out of
    _format_detections_json (BACK-1248) so --also-json can write the exact
    document --format json prints, rather than a second shape.
    """
    from reveal.utils.results import add_cli_contract_fields

    result = {
        'file': path,
        'detections': [
            d.to_dict(no_snippets=no_snippets, max_snippet_chars=max_snippet_chars)
            for d in detections
        ],
        'total': len(detections)
    }
    if total_available is not None and total_available != len(detections):
        result['meta'] = {
            'truncated': True,
            'total_available': total_available,
            'returned': len(detections),
        }
    if parse_degraded:
        result['warning'] = (
            "file did not parse cleanly; results may be incomplete or incorrect"
        )
    if rule_errors:
        result['errors'] = rule_errors
    return add_cli_contract_fields(
        result, result_type='check', source=path, source_type='file',
    )


def _format_detections_grep(detections: List[Any]) -> None:
    """Format detections as grep output.

    Args:
        detections: List of Detection objects
    """
    for d in detections:
        print(f"{d.file_path}:{d.line}:{d.column}:{d.rule_code}:{d.message}")


def _format_detections_text(
    path: str,
    detections: List[Any],
    no_group: bool = False,
    parse_degraded: bool = False,
    rule_errors: Optional[List[dict]] = None,
    no_snippets: bool = False,
    max_snippet_chars: Optional[int] = None,
    total_available: Optional[int] = None,
) -> None:
    """Format detections as human-readable text.

    When a rule fires >= _GROUP_THRESHOLD times, collapses to a single summary
    line to keep output scannable.  Use --no-group to expand everything.

    Args:
        path: File path
        detections: List of Detection objects (already max-items-truncated
            by the caller, if requested — this just renders what it's given)
        no_group: Disable collapsing of repeated rules
        parse_degraded: True when the parser recovered from a syntax error —
            see _format_detections_json (BACK-1083).
        rule_errors: Rules that raised during check() — see _format_detections_json.
        no_snippets: Omit the 📝 code-excerpt line (BACK-1182).
        max_snippet_chars: Truncate the excerpt to N chars instead of
            omitting it (BACK-1181). Ignored when no_snippets.
        total_available: True detection count before any --max-items
            truncation, if different from len(detections) (BACK-1181).
    """
    for err in rule_errors or []:
        print(f"{path}: ⚠️  rule {err['rule']} crashed and did not run — {err['error']}")

    if not detections:
        if parse_degraded:
            print(f"{path}: ⚠️  file did not parse cleanly — results may be incomplete or incorrect")
        else:
            print(f"{path}: ✅ No issues found")
        return

    count = len(detections)
    if parse_degraded:
        print(f"{path}: ⚠️  file did not parse cleanly — results below may be incomplete or incorrect")
    print(f"{path}: Found {count} issue{'s' if count != 1 else ''}\n")

    def _print_truncation_footer():
        if total_available is not None and total_available > count:
            print(f"… +{total_available - count} more issue(s) hidden (--max-items {count})\n")

    if no_group or count < _GROUP_THRESHOLD:
        for d in sorted(detections, key=lambda x: (x.line, x.column)):
            print(d.render(no_snippets=no_snippets, max_snippet_chars=max_snippet_chars))
            print()
        _print_truncation_footer()
        return

    # Group by rule_code to find repeated rules
    by_rule: dict = defaultdict(list)
    for d in detections:
        by_rule[d.rule_code].append(d)

    collapsed: set = {code for code, group in by_rule.items() if len(group) >= _GROUP_THRESHOLD}
    shown_collapsed: set = set()

    for d in sorted(detections, key=lambda x: (x.line, x.column)):
        if d.rule_code not in collapsed:
            print(d.render(no_snippets=no_snippets, max_snippet_chars=max_snippet_chars))
            print()
        elif d.rule_code not in shown_collapsed:
            shown_collapsed.add(d.rule_code)
            total = len(by_rule[d.rule_code])
            print(d.render(no_snippets=no_snippets, max_snippet_chars=max_snippet_chars))
            print(f"\n  ↳ +{total - 1} more {d.rule_code} occurrences hidden — use --no-group to expand\n")
    _print_truncation_footer()


def run_pattern_detection(
    analyzer: FileAnalyzer,
    path: str,
    output_format: str,
    args: Any,
    config: Optional[Any] = None
) -> int:
    """Run pattern detection rules on a file.

    Args:
        analyzer: File analyzer instance
        path: File path
        output_format: Output format ('text', 'json', 'grep')
        args: CLI arguments (for --select, --ignore)
        config: Optional RevealConfig for breadcrumb settings

    Returns:
        (detection_count, degraded) tuple. `degraded` is True when the file
        did not parse cleanly (BACK-1083's parse_degraded, tree-sitter
        error-recovery) or a rule raised (rule_errors) -- meaning
        `detection_count` may be incomplete/wrong, not a trustworthy
        "clean" signal. Added for BACK-1099's exit-code contract: a caller
        that only wants the old int should unpack `count, _ = run_pattern_detection(...)`.
    """
    from .rules import RuleRegistry

    # Parse select/ignore options
    select = args.select.split(',') if args.select else None
    ignore = args.ignore.split(',') if args.ignore else None
    no_group = getattr(args, 'no_group', False)
    no_snippets = getattr(args, 'no_snippets', False)
    severity_arg = getattr(args, 'severity', None)

    # Get structure and content
    structure = analyzer.get_structure()
    content = analyzer.content

    # Warn about auto-generated files (but still check — user asked explicitly)
    if output_format == 'text' and _is_generated_file(content):
        print(f"{path}: ℹ️  Auto-generated file detected — results may include unfixable issues\n"
              f"  💡 Add '# reveal: generated' near the top to suppress in recursive checks\n")

    # Run rules
    rule_errors: List[dict] = []
    detections = RuleRegistry.check_file(
        path, structure, content, select=select, ignore=ignore, errors=rule_errors
    )
    # BACK-1083: a tree-sitter recovery parse (structure['_has_errors'], set by
    # BACK-1084) means rules ran against fabricated/partial structure — surface
    # that instead of letting "0 detections" read as "clean file".
    parse_degraded = isinstance(structure, dict) and bool(structure.get('_has_errors'))

    # Apply severity filter if requested
    if severity_arg:
        _SEVERITY_ORDER = ['low', 'medium', 'high', 'critical']
        level = severity_arg.lower()
        if level not in _SEVERITY_ORDER:
            print(f"Warning: unknown --severity '{severity_arg}'. Valid levels: {', '.join(_SEVERITY_ORDER)}",
                  file=sys.stderr)
        else:
            min_idx = _SEVERITY_ORDER.index(level)
            detections = [d for d in detections
                          if _SEVERITY_ORDER.index(d.severity.value) >= min_idx]

    # BACK-1181: --max-items caps what's RENDERED, not the true count -- the
    # return value below (and thus check_exit_code's total_issues) must
    # still reflect reality, or a truncated view could silently mask
    # findings from the exit code / summary.
    max_items = getattr(args, 'max_items', None)
    max_snippet_chars = getattr(args, 'max_snippet_chars', None)
    total_available = len(detections)
    rendered_detections = detections
    if max_items is not None and total_available > max_items:
        rendered_detections = detections[:max_items]

    # Format and output results
    formatters = {
        'json': lambda: _format_detections_json(
            path, rendered_detections, parse_degraded=parse_degraded, rule_errors=rule_errors,
            no_snippets=no_snippets, max_snippet_chars=max_snippet_chars,
            total_available=total_available,
        ),
        'grep': lambda: _format_detections_grep(detections),
        'text': lambda: _format_detections_text(
            path, rendered_detections, no_group=no_group, parse_degraded=parse_degraded, rule_errors=rule_errors,
            no_snippets=no_snippets, max_snippet_chars=max_snippet_chars,
            total_available=total_available,
        ),
    }

    formatter = formatters.get(output_format, formatters['text'])
    formatter()

    # BACK-1248: --also-json on a single file. Built from the same detections
    # the renderer just used -- no second analysis pass -- and deliberately the
    # same document `--format json` prints for this invocation, so the artifact
    # never depends on which --format the human report happened to use.
    # isinstance rather than truthiness: `args` is a Mock in several callers'
    # tests, and getattr on a Mock returns a truthy Mock for any attribute.
    also_json = getattr(args, 'also_json', None)
    if isinstance(also_json, (str, os.PathLike)) and output_format != 'json':
        try:
            with open(also_json, 'w') as f:
                f.write(safe_json_dumps(_build_detections_json(
                    path, rendered_detections, parse_degraded=parse_degraded,
                    rule_errors=rule_errors, no_snippets=no_snippets,
                    max_snippet_chars=max_snippet_chars,
                    total_available=total_available,
                )))
        except OSError as e:
            print(f"Warning: --also-json could not write {also_json}: {e}", file=sys.stderr)

    # Print breadcrumbs after text output (not for json/grep)
    if output_format == 'text':
        file_type = get_file_type_from_analyzer(analyzer)
        print_breadcrumbs('quality-check', path, file_type=file_type, config=config,
                         detections=detections)

    degraded = parse_degraded or bool(rule_errors)
    return len(detections), degraded


def run_schema_validation(
    analyzer: FileAnalyzer,
    path: str,
    schema_name: str,
    output_format: str,
    args: Any
) -> None:
    """Run schema validation on front matter.

    Args:
        analyzer: File analyzer instance
        path: File path
        schema_name: Schema name or path to schema file
        output_format: Output format ('text', 'json', 'grep')
        args: CLI arguments (for --select, --ignore)
    """
    from .schemas.frontmatter import load_schema
    from .rules.frontmatter import set_validation_context, clear_validation_context
    from .rules import RuleRegistry
    from .registry import get_markdown_extensions

    # Check if file is markdown (schema validation is for markdown front matter)
    if not path.lower().endswith(tuple(get_markdown_extensions())):
        print("Warning: Schema validation is designed for markdown files", file=sys.stderr)
        print(f"         File '{path}' does not appear to be markdown", file=sys.stderr)
        print("         Continuing anyway...\n", file=sys.stderr)

    # Load schema
    schema = load_schema(schema_name)
    if not schema:
        print(f"Error: Schema '{schema_name}' not found", file=sys.stderr)
        print("\nAvailable built-in schemas:", file=sys.stderr)
        from .schemas.frontmatter import list_schemas
        for name in list_schemas():
            print(f"  - {name}", file=sys.stderr)
        print("\nOr provide a path to a custom schema file", file=sys.stderr)
        sys.exit(1)

    # Get structure with frontmatter extraction enabled
    structure = analyzer.get_structure(extract_frontmatter=True)
    content = analyzer.content

    # Set schema context for F-series rules
    set_validation_context(schema)

    try:
        # Parse select/ignore options (default to F-series rules if not specified)
        select = args.select.split(',') if args.select else ['F']
        ignore = args.ignore.split(',') if args.ignore else None

        # Run rules (F003, F004, F005 will use the schema context)
        detections = RuleRegistry.check_file(
            path, structure, content, select=select, ignore=ignore
        )

        # Format and output results
        formatters = {
            'json': lambda: _format_detections_json(path, detections),
            'grep': lambda: _format_detections_grep(detections),
            'text': lambda: _format_detections_text(path, detections),
        }

        formatter = formatters.get(output_format, formatters['text'])
        formatter()

        # Exit with error code if validation failed
        if detections:
            sys.exit(1)

    finally:
        # Always clear context, even if an error occurred
        clear_validation_context()
